"""Parity tests: the Python port must match the original TS engine exactly.

``fixtures.json`` is generated by ``scripts/generate_fixtures.ts`` using the
verbatim original hash/selection/reading algorithms. If these tests fail, the
Python port has diverged and would remap users' symbols/readings.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.core.hash import simple_hash
from app.core.reading_engine import generate_reading
from app.core.symbol_selector import select_symbol

FIXTURE = json.loads((Path(__file__).parent / "fixtures.json").read_text(encoding="utf-8"))


@pytest.mark.parametrize("case", FIXTURE["hash"], ids=lambda c: repr(c["input"]))
def test_hash_parity(case):
    assert simple_hash(case["input"]) == case["hash"]


@pytest.mark.parametrize(
    "case",
    FIXTURE["selection"],
    ids=lambda c: f'{c["topic"]}-{c["emotion"]}-{c["dateString"]}',
)
def test_symbol_selection_parity(case):
    assert select_symbol(case["topic"], case["emotion"], case["dateString"]) == case["symbolId"]


@pytest.mark.parametrize(
    "case",
    FIXTURE["reading"],
    ids=lambda c: f'{c["topic"]}-{c["emotion"]}-{c["locale"]}',
)
def test_reading_parity(case):
    result = generate_reading(
        topic=case["topic"],
        emotion=case["emotion"],
        symbol_id=case["symbolId"],
        locale=case["locale"],
    )
    assert result == case["result"]
