"""Loads the JSON data tables exported from the original TypeScript app.

The JSON files under ``app/data/`` are generated by ``scripts/export_data.ts``
and must not be hand-edited. Re-run the exporter to regenerate them.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def _load(name: str) -> Any:
    with open(DATA_DIR / name, encoding="utf-8") as fh:
        return json.load(fh)


@lru_cache(maxsize=1)
def _symbols_payload() -> dict[str, Any]:
    return _load("symbols.json")


@lru_cache(maxsize=1)
def symbol_ids() -> list[str]:
    """Ordered list of symbol ids. Order is significant for hashing."""
    return list(_symbols_payload()["symbolIds"])


@lru_cache(maxsize=1)
def symbols_by_id() -> dict[str, dict[str, Any]]:
    return {s["id"]: s for s in _symbols_payload()["symbols"]}


def get_symbol(symbol_id: str) -> dict[str, Any]:
    symbols = symbols_by_id()
    if symbol_id not in symbols:
        raise KeyError(f'Unknown SymbolId: "{symbol_id}"')
    return symbols[symbol_id]


@lru_cache(maxsize=1)
def emotional_mirrors() -> dict[str, Any]:
    return _load("emotional_mirrors.json")


@lru_cache(maxsize=1)
def blind_spots() -> dict[str, Any]:
    return _load("blind_spots.json")


@lru_cache(maxsize=1)
def closing_lines() -> dict[str, Any]:
    return _load("closing_lines.json")


@lru_cache(maxsize=1)
def translations() -> dict[str, Any]:
    return _load("translations.json")
